package:
    name: NAME
    version: VERSION
source:
    git_url: 'https://github.com/Lucaszw/microdrop-feedstock'
requirements:
    build:
        - 'python 2.7*'
        - 'nodejs >=8'
        - git
        - gulp
    run:
        - 'python 3*'
        - 'nodejs >=8'
build:
    script: 'gulp conda:build'
about:
    home: 'https://github.com/sci-bots/microdrop-3.0'
    license: BSD
    license_file: LICENSE
