package:
    name: NAME
    version: VERSION
source:
    git_url: .
requirements:
    build:
        - 'python 3*'
        - 'nodejs >=8'
    run:
        - 'python 3*'
        - 'nodejs >=8'
build:
    script: 'npm i --global gulp && npm i && gulp conda:build'
about:
    home: 'https://github.com/sci-bots/microdrop-3.0'
    license: BSD
    license_file: LICENSE
